apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: matrikkel-kafka-light
  namespace: matrikkel-main
spec:
  image: "{{ image }}"
  port: 8081
  ingresses:
    - matrikkel-kafka-light.atkv3-dev.kartverket-intern.cloud
  replicas: 1

  liveness:
    port: 8081
    path: /internal/isAlive
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  readiness:
    port: 8081
    path: /internal/isReady
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  prometheus:
    port: 8081
    path: /internal/metrics
    allowAllMetrics: true

  azure:
    application:
      enable: true

  env:
    - name: VERSION
      value: "{{ version }}"
    - name: DB_URL
      value: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    - name: DB_USER_USERNAME
      value: "sa"
    - name: DB_USER_PASSWORD
      value: ""
    - name: DB_ADMIN_USERNAME
      value: "sa"
    - name: DB_ADMIN_PASSWORD
      value: ""