apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: matrikkel-kafka-light
  namespace: matrikkel-prodtest
spec:
  image: "{{ image }}"
  port: 8081
  ingresses:
    - matrikkel-kafka-light-prodtest.atkv3-prod.kartverket-intern.cloud
  replicas: 1

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

  liveness:
    port: 8081
    path: /internal/isAlive
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  readiness:
    port: 8081
    path: /internal/isReady
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  prometheus:
    port: 8081
    path: /internal/metrics
    allowAllMetrics: true

  azure:
    application:
      enabled: true

  databases:
    - name: matrikkel-kafka-light
      envName: DB_URL

  env:
    - name: VERSION
      value: "{{ version }}"
    - name: DB_USER_USERNAME
      value: "kafka_light_user"
    - name: DB_USER_PASSWORD
      gsmSecretName: "prodtest-matrikkel-kafka-light-db-user-password"
    - name: DB_ADMIN_USERNAME
      value: "kafka_light_admin"
    - name: DB_ADMIN_PASSWORD
      gsmSecretName: "prodtest-matrikkel-kafka-light-db-admin-password"