[versions]
kotlin = "2.3.21"
logback = "1.5.33"
flywayVersion = "12.6.2"
postgresqlVersion = "42.7.11"
hikariVersion = "7.0.2"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

flyway = { module = "org.flywaydb:flyway-core", version.ref = "flywayVersion" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flywayVersion" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikariVersion" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresqlVersion" }
h2 = { module = "com.h2database:h2", version = "2.4.240"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

