[versions]
kotlin = "2.4.0"
flywayVersion = "12.8.1"
testcontainers = "1.21.4"
junitVersion = "6.1.0"
heimdallCommonVersion = "1.2026.06.11-11.28-8cbbed0"

[libraries]
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.18" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.34" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerializationPlugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
ktorUtils = { module = "no.kartverket.heimdall.common:ktor-utils", version.ref = "heimdallCommonVersion"}

flyway = { module = "org.flywaydb:flyway-core", version.ref = "flywayVersion" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flywayVersion" }
hikari = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.11" }
h2 = { module = "com.h2database:h2", version = "2.4.240"}
kotliquery = { module = "com.github.seratch:kotliquery", version = "1.9.1" }
micrometerPrometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.17.0" }

junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVersion" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitVersion" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitVersion" }
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version = "0.28.1" }
mockk = { module = "io.mockk:mockk", version = "1.14.11" }

testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[bundles]
testEcosystem = [
    "logback-classic",
    "junitApi",
    "junitEngine",
    "junitParams",
    "assertk",
    "mockk",
    "testcontainers-postgres",
    "testcontainers-junit",
    "junitPlatformLauncher"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

